services:
  rosnoetic:
    container_name: rosnoetic
    hostname: rosnoetic
    build:
      context: ./
      dockerfile: Dockerfile
      shm_size: 2gb
    shm_size: 2gb
    environment:
      - RESOLUTION=1920x1080
    volumes:
      - /catkin_ws/src:/root/catkin_ws/src
      - ~/src:/root/src
    stdin_open: true
    tty: true
    ports:
      - 6080:80
      - 6079:6079
      - 46375:46375
      - 11311:11311
