version: "3.9"

services:
  rosnoetic:
    container_name: rosnoetic
    hostname: rosnoetic
    build:
      context: ./ros
      dockerfile: Dockerfile
    environment:
      - RESOLUTION=1440x900
      - DISPLAY=display:0
    volumes:
      - ~/catkin_ws/src:/app/catkin_ws/src
      - ~/src:/app/src
    stdin_open: true
    tty: true
    ports:
      - 6080:80
      - 6079:6079
      - 46375:46375
      - 11311:11311
    extra_hosts:
      - "display:host-gateway"
    networks:
      - default
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0

networks:
  default:
    driver: bridge
