services:
  ros1_noetic:
    container_name: ros1_noetic
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '2gb'
    shm_size: '2gb'
    environment:
      - DISPLAY=localhost:0.0
    volumes:
      - ~/ursim:/root/ursim
      - ~/catkin_ws/src:/root/catkin_ws/src
      - ~/src:/root/src
    command: bash run.sh
    stdin_open: true
    tty: true
    ports:
      - 6080:6080
      - 46375:46375
      - 11311:11311