services:
  ros1_noetic:
    container_name: ros1_noetic
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=localhost:0.0
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ~/ursim:/root/ursim
      - ~/catkin_ws:/root/catkin_ws
      - ~/src:/root/src 
    command: bash run.sh
    stdin_open: true
    tty: true
    ports:
      - 46375:46375
      - 11311:11311